source $lib_dir/helper_functions.sh

CheckConfig
CheckPermissons
DefineDistro

source $lib_dir/config_functions.sh

LoadConfig

source $lib_dir/handler_functions.sh

HandlePackagesRemoval
HandleFlatpakPackages
HandlePackages
HandleSourcedPackages

HandleSystemFiles
HandleSystemFilesFromTo
HandleSystemDirectories
HandleSystemDirectoriesFromTo

HandleGroups
HandleUsers

HandleUserFiles
HandleUserFilesFromTo
HandleUserDirectories
HandleUserDirectoriesFromTo

HandleSystemdUnits

HandleSSHGenKeys
HandleSSHAddkeys
