source $lib_dir/helper_functions.sh

CheckConfig
CheckPermissons
DefineDistro

source $lib_dir/config_functions.sh
source $lib_dir/asdf_config_functions.sh

LoadConfig

source $lib_dir/handler_functions.sh

HandlePackagesRemoval
HandleFlatpakPackages
HandlePreInstallASDF

HandlePackages
HandleSourcedPackages

HandlePostInstallASDF

HandleASDFPlugins

HandleSystemFiles
HandleSystemFilesFromTo
HandleSystemDirectories
HandleSystemDirectoriesFromTo

HandleGroups
HandleUsers

HandleUserFiles
HandleUserFilesFromTo
HandleUserDirectories
HandleUserDirectoriesFromTo

HandleSystemdUnits

HandleSSHGenKeys
HandleSSHAddkeys

Info "Installation complete"
