name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  debian:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build DEB
      run: |
        VERSION=${{ github.ref_name }}
        VERSION=${VERSION:1}
        sed "s/VERSION/$VERSION/" build/debian/DEBIAN/control
        mkdir -p build/debian/usr/
        mkdir -p build/debian/usr/bin/
        mkdir -p build/debian/usr/lib/
        mv setuper build/debian/usr/bin/
        mv lib/ build/debian/usr/lib/setuper
        cd build/debian
        dpkg-deb --build setuper

    - name: Upload DEB
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/debian/setuper.deb

  arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      volumes:
        - ./build/arch:/build

    steps:
    - uses: actions/checkout@v2

    - name: Build arch
      run: |
        VERSION=${{ github.ref_name }}
        VERSION=${VERSION:1}
        sed -i "s/VERSION/$VERSION/" build/arch/PKGBUILD
        mkdir -p build/arch/src
        mv setuper build/arch/src/
        mv lib/ build/arch/src/
        cd build/arch
        useradd --no-create-home build
        chown -R build:build ./
        sudo -u build makepkg
        mv setuper-$VERSION-1-any.pkg.tar.zst setuper.pkg.tar.zst

    - name: Upload arch
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/arch/setuper.pkg.tar.zst
