name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  debian:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build DEB
      run: |
        mkdir setuper_${{ github.ref_name }}
        mkdir setuper_${{ github.ref_name }}/DEBIAN
        mkdir setuper_${{ github.ref_name }}/usr
        mkdir setuper_${{ github.ref_name }}/usr/lib/
        mkdir setuper_${{ github.ref_name }}/usr/bin/
        mv build/debian/control setuper_${{ github.ref_name }}/DEBIAN/control
        mv setuper setuper_${{ github.ref_name }}/usr/bin/
        mv lib/ setuper_${{ github.ref_name }}/usr/lib/setuper
        dpkg-deb --build setuper_${{ github.ref_name }}

    - name: Upload DEB
      uses: softprops/action-gh-release@v2
      with:
        files: setuper_${{ github.ref_name }}.deb

  arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      volumes:
        - ./build/arch:/build

    steps:
    - uses: actions/checkout@v2

    - name: Build arch
      run: |
        mkdir -p ./build/arch/src
        cp ./setuper ./build/arch/src/
        cp -r ./lib/ ./build/arch/src/
        cd ./build/arch

        echo "Setup user"
        useradd --no-create-home build

        echo "Setting permissions"
        chown -R build:build ./

        echo "Setting permissions for everyone"
        chmod -R 777 ./

        echo "Building package"
        sudo -u build makepkg

        ls -la

    - name: Upload arch
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/arch/setuper_${{GITHUB_REF_NAME#v}}-1-any.pkg.tar.zst
