name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  debian:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build DEB
      run: |
        mkdir setuper_${{ github.ref_name }}
        mkdir setuper_${{ github.ref_name }}/DEBIAN
        mkdir setuper_${{ github.ref_name }}/usr
        mkdir setuper_${{ github.ref_name }}/usr/lib/
        mkdir setuper_${{ github.ref_name }}/usr/bin/
        mv build/debian_control setuper_${{ github.ref_name }}/DEBIAN/control
        mv setupper setuper_${{ github.ref_name }}/usr/bin/
        mv lib/ setuper_${{ github.ref_name }}/usr/lib/setupper
        dpkg-deb --build setuper_${{ github.ref_name }}

    - name: Upload DEB
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: setuper_${{ github.ref_name }}.deb
